# Generated by Django 3.2.18 on 2023-03-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Модель'),
        ),
    ]
